// src/utils/achievementMap.ts
// Auto-generated map of milestone ID → display info for AchievementModal rendering.  
// This keeps all achievement metadata in one place and makes it easy to look up icons, titles etc when rendering the user's achievements list or the milestone progress modal.
// Keep in sync with MILESTONES array in app/achievements.tsx.
import type { AchievementInfo } from '@/components/AchievementModal';

export const ACHIEVEMENT_MAP: Record<string, AchievementInfo> = {
  'first_step': { id: 'first_step', title: 'First Step', description: 'Log your very first activity', icon: 'shoe-prints', color: '#4CAF50' },
  'all_categories': { id: 'all_categories', title: 'All-Rounder', description: 'Log at least one activity in every category', icon: 'apps', lib: 'Ionicons', color: '#AB47BC' },
  'variety_week': { id: 'variety_week', title: 'Eco Polymath', description: 'Log all 5 activity types in a single week', icon: 'star-four-points', lib: 'MCO', color: '#6A1B9A' },
  'streak_3': { id: 'streak_3', title: 'Heat Wave', description: 'Keep a 3-day streak', icon: 'fire-flame-simple', color: '#FF7043' },
  'streak_7': { id: 'streak_7', title: 'Weekly Warrior', description: 'Keep a 7-day streak', icon: 'fire-flame-curved', color: '#F4511E' },
  'streak_14': { id: 'streak_14', title: 'Fortnight Force', description: 'Keep a 14-day streak', icon: 'fire', color: '#E64A19' },
  'streak_30': { id: 'streak_30', title: 'Solar Flare', description: 'Keep a 30-day streak', icon: 'sunny', lib: 'Ionicons', color: '#FFB300' },
  'streak_60': { id: 'streak_60', title: 'Unstoppable', description: 'Keep a 60-day streak', icon: 'lightning-bolt', lib: 'MCO', color: '#BF360C' },
  'streak_100': { id: 'streak_100', title: 'Centurion', description: 'Keep a 100-day streak', icon: 'infinity', color: '#880E4F' },
  'token_100': { id: 'token_100', title: 'Token Starter', description: 'Earn 100 EcoTokens', icon: 'leaf', color: '#43A047' },
  'token_500': { id: 'token_500', title: 'Token Collector', description: 'Earn 500 EcoTokens', icon: 'sprout', lib: 'MCO', color: '#FBC02D' },
  'token_1000': { id: 'token_1000', title: 'Token Hoarder', description: 'Earn 1,000 EcoTokens', icon: 'tree', color: '#F57F17' },
  'token_2500': { id: 'token_2500', title: 'Token Titan', description: 'Earn 2,500 EcoTokens', icon: 'star', color: '#FB8C00' },
  'token_5000': { id: 'token_5000', title: 'EcoVerse Legend', description: 'Earn 5,000 EcoTokens', icon: 'pine-tree', lib: 'MCO', color: '#FF6F00' },
  'token_10000': { id: 'token_10000', title: 'Token Master', description: 'Earn 10,000 EcoTokens lifetime', icon: 'crown', color: '#F9A825' },
  'token_25000': { id: 'token_25000', title: 'EcoVerse Elite', description: 'Earn 25,000 EcoTokens lifetime', icon: 'shield-crown', lib: 'MCO', color: '#E65100' },
  'co2_1': { id: 'co2_1', title: 'Carbon Cutter', description: 'Save 1 kg of CO₂', icon: 'scissors', color: '#66BB6A' },
  'co2_10': { id: 'co2_10', title: 'Climate Conscious', description: 'Save 10 kg of CO₂', icon: 'earth-americas', color: '#2E7D32' },
  'co2_50': { id: 'co2_50', title: 'CO₂ Crusader', description: 'Save 50 kg of CO₂', icon: 'leaf-circle', lib: 'MCO', color: '#1B5E20' },
  'co2_100': { id: 'co2_100', title: 'Carbon Slayer', description: 'Save 100 kg of CO₂', icon: 'earth-europe', color: '#00695C' },
  'co2_250': { id: 'co2_250', title: 'Climate Champion', description: 'Save 250 kg of CO₂', icon: 'globe', lib: 'Ionicons', color: '#004D40' },
  'co2_1000': { id: 'co2_1000', title: 'Carbon Warrior', description: 'Save 1,000 kg of CO₂', icon: 'planet', lib: 'Ionicons', color: '#1A237E' },
  'walking_first': { id: 'walking_first', title: 'First Steps', description: 'Log your first walk', icon: 'person-walking', color: '#4CAF50' },
  'walking_marathon': { id: 'walking_marathon', title: 'Marathon Walker', description: 'Log 50 walking activities', icon: 'walk', lib: 'MCO', color: '#2E7D32' },
  'running_first': { id: 'running_first', title: 'Off the Blocks', description: 'Log your first run', icon: 'person-running', color: '#FF7043' },
  'running_50': { id: 'running_50', title: 'Pavement Pounder', description: 'Log 50 running activities', icon: 'run', lib: 'MCO', color: '#E64A19' },
  'cycling_first': { id: 'cycling_first', title: 'Wheel Life', description: 'Log your first cycle ride', icon: 'bicycle', color: '#29B6F6' },
  'cycling_century': { id: 'cycling_century', title: 'Cycle Century', description: 'Log 30 cycling activities', icon: 'bike', lib: 'MCO', color: '#0277BD' },
  'electricity_first': { id: 'electricity_first', title: 'Power Saver', description: 'Log your first electricity saving', icon: 'bolt', color: '#FFC107' },
  'electricity_25': { id: 'electricity_25', title: 'Grid Buster', description: 'Log 25 electricity savings', icon: 'lightning-bolt-circle', lib: 'MCO', color: '#F9A825' },
  'water_first': { id: 'water_first', title: 'Drop Counter', description: 'Log your first water saving', icon: 'droplet', color: '#26C6DA' },
  'water_25': { id: 'water_25', title: 'Flow Stopper', description: 'Log 25 water savings', icon: 'water', lib: 'Ionicons', color: '#0097A7' },
  'activities_10': { id: 'activities_10', title: 'Getting Started', description: 'Log 10 activities', icon: 'clipboard-check', color: '#29B6F6' },
  'activities_25': { id: 'activities_25', title: 'Consistent', description: 'Log 25 activities', icon: 'calendar-check', color: '#5C6BC0' },
  'activities_50': { id: 'activities_50', title: 'Eco Veteran', description: 'Log 50 activities', icon: 'shield-checkmark', lib: 'Ionicons', color: '#0288D1' },
  'activities_100': { id: 'activities_100', title: 'Century Club', description: 'Log 100 activities', icon: 'medal', color: '#7B1FA2' },
  'activities_200': { id: 'activities_200', title: 'Dedicated', description: 'Log 200 activities', icon: 'analytics', lib: 'Ionicons', color: '#00838F' },
  'activities_500': { id: 'activities_500', title: 'Eco Obsessed', description: 'Log 500 activities', icon: 'rocket', color: '#283593' },
};